exp_name = "myenv"
seed = 1234
track = false
wandb_project_name = "cleanRL"
wandb_entity = "null"
capture_video = false
save_model = false
upload_model = false
hf_entity = ""
env_id = "MyEnv-v0"
total_timesteps = 1000000
learning_rate = 0.0003
buffer_size = 1000000
gamma = 0.99
tau = 0.005
batch_size = 256
exploration_noise = 0.1
learning_starts = 25000.0
policy_frequency = 2
noise_clip = 0.5
adam_beta1 = 0.9
adam_beta2 = 0.999
epsilon = 1e-8
