adam_beta1 = 0.9
adam_beta2 = 0.999
batch_size = 36
buffer_size = 5000
capture_video = false
env_id = "MyEnv-v0"
epsilon = 1e-8
exp_name = "myenv"
exploration_noise = 0.01
gamma = 0.01
hf_entity = ""
learning_rate = 0.001
learning_starts = 5
noise_clip = 0.5
policy_frequency = 50
save_model = false
seed = 1234
tau = 0.005
total_timesteps = 5000
track = false
upload_model = false
wandb_entity = "null"
wandb_project_name = "cleanRL"
